chore: Fix nightly build (aside from verification)
aws/aws-database-encryption-sdk-dynamodb pull request #1029
Opened 2024-05-16 15:49 UTC by robin-aws

*Description of changes:*

Makes the same changes around avoiding direct calls to instantiate parameterized datatypes in Java code as in https://github.com/aws/aws-cryptographic-material-providers-library/pull/195, plus some CI configuration fixes.

Dry runs of nightly builds:
* [Library Java tests](https://github.com/aws/aws-database-encryption-sdk-dynamodb/actions/runs/9104958211)
* [Java Examples](https://github.com/aws/aws-database-encryption-sdk-dynamodb/actions/runs/9106211948)
* [test dotnet](https://github.com/aws/aws-database-encryption-sdk-dynamodb/actions/runs/9100864042)

Will leave fixing the verification for a separate PR since this was already a fair bit of work :)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-05-16 23:45 UTC, texastony requested changes

2024-05-16 23:45 UTC, texastony commented on DynamoDbEncryption/runtimes/java/src/main/java/software/amazon/cryptography/dbencryptionsdk/dynamodb/itemencryptor/internaldafny/legacy/InternalLegacyOverride.java
> +import Dafny.Aws.Cryptography.Primitives.Types.InternalResult;
Blocking/Issue: This is from the Primitives library, not the Standard Library or this Library (DB-ESDK).

That concerns me.
Can you explain why a Type defined in the Primitives Library is being used here?

I have a hard time believing that all the cases that you return a `InternalResult` always yield a class related to the Cryptographic Primitives Library.

2024-05-16 23:54 UTC, robin-aws commented on DynamoDbEncryption/runtimes/java/src/main/java/software/amazon/cryptography/dbencryptionsdk/dynamodb/itemencryptor/internaldafny/legacy/InternalLegacyOverride.java
> +import Dafny.Aws.Cryptography.Primitives.Types.InternalResult;
I introduced that `InternalResult` type when fixing up the primitives library, but it's just as generic as the Dafny `Result<T, E>` type: https://github.com/aws/aws-cryptographic-material-providers-library/blob/main/AwsCryptographyPrimitives/runtimes/java/src/main/java/Dafny/Aws/Cryptography/Primitives/Types/InternalResult.java#L3-L13

I didn't spot where I defined it when I imported it to solve the same problem here. It really should be in the Standard Library instead. But moving it there now in the MPL wouldn't fix the reference here until the next MPL launch so we can update the submodule.

I can just add a comment for now.

2024-05-17 00:11 UTC, texastony commented on DynamoDbEncryption/runtimes/java/src/main/java/software/amazon/cryptography/dbencryptionsdk/dynamodb/itemencryptor/internaldafny/legacy/InternalLegacyOverride.java
> +import Dafny.Aws.Cryptography.Primitives.Types.InternalResult;
1. I am happy I did not approve https://github.com/aws/aws-cryptographic-material-providers-library/pull/195. I get to continue to feel superior. 
2. an MPL release is going to go out very soon... go fix this now, and this PR can land correctly

2024-06-04 18:26 UTC, seebees approved these changes
LGTM

2024-06-04 22:30 UTC, texastony approved these changes

2024-06-04 22:32 UTC, merged