feat: allow indirect attribute names with MultiKeyStore
aws/aws-database-encryption-sdk-dynamodb pull request #1208
Opened 2024-07-19 16:07 UTC by ajewellamz

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-07-19 16:28 UTC, seebees requested changes
Just a bit of housekeeping

2024-07-19 16:28 UTC, seebees commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/FilterExpr.dfy
Shouldn't this be in the spec somewhere?

2024-07-19 16:28 UTC, seebees commented on DynamoDbEncryption/dafny/DynamoDbEncryption/test/BeaconTestFixtures.dfy
> +    | MultiLoc (keyName : string, deleteKey : bool)
I don't think you are using this? `SI.MultiLoc` is the type right?
```suggestion
```

2024-07-19 16:28 UTC, seebees commented on DynamoDbEncryption/dafny/DynamoDbEncryption/test/DDBSupport.dfy
> +//                 .build();
```suggestion
```

2024-07-19 16:28 UTC, seebees commented on DynamoDbEncryption/dafny/DynamoDbEncryption/test/DDBSupport.dfy
> +                                message := "Need KeyId because of beacon std2 but no KeyId found in query"));
So this is failing because there is a beacon `std2` but there is no information about what beacon key to use?

```suggestion
    // Verify that if there is no branch key id information that a query for a beacon will fail.
    queryInput := DDB.QueryInput (
      TableName := "foo",
      ExpressionAttributeValues := Some(expressionAttributeValues),
      KeyConditionExpression := Some("std2 = :other")
    );
    var result2 := QueryInputForBeacons(Some(search), FullTableConfig.attributeActionsOnEncrypt, queryInput);
    expect result2 == Failure(AwsCryptographyDbEncryptionSdkDynamoDbTypes.Error.DynamoDbEncryptionException(
                                message := "Need KeyId because of beacon std2 but no KeyId found in query"));
```

2024-07-19 16:40 UTC, texastony commented on DynamoDbEncryption/dafny/DynamoDbEncryption/test/BeaconTestFixtures.dfy
> +  method GetMultiKeyStore() returns (output : SI.ValidStore)
Question: How is this a multi-store as compared to just a Key Store?

Is it that this particular "logical" Key Store has numerous Branch Key IDs in it,
all protected by the same `kms-arn`?

Or is it just a Key Store, 
and the consuming methods,
like `GetLotsaBeaconsMulti`,
then use it to build a Multi Store?

2024-07-19 16:40 UTC, texastony commented on DynamoDbEncryption/dafny/DynamoDbEncryption/test/DDBSupport.dfy
> +  function method DS(x : string) : DDB.AttributeValue
Question: `DS` is a tough name... 
I think you are going for "data string", right?

```suggestion
  // data string :: cast string to DDB.AttributeValue.S
  function method DS(x : string) : DDB.AttributeValue
```

2024-07-22 16:25 UTC, seebees approved these changes
LGTM

2024-07-22 17:20 UTC, merged