feat(SharedCache): Shared Cache for Searchable Encryption
aws/aws-database-encryption-sdk-dynamodb pull request #1476
Opened 2024-11-20 20:52 UTC by RitvikKapila

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-11-20 23:58 UTC, RitvikKapila commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/ConfigToInfo.dfy
> +    // TODO : Add check that customers only provide either cacheTTL or cache in case of SingleKeyStore
Also for `MultiKeyStore`

2024-11-22 01:01 UTC, RitvikKapila commented on DynamoDbEncryption/dafny/DynamoDbEncryption/Model/DynamoDbEncryption.smithy
> +  @javadoc("How long (in seconds) the beacon key material is cached locally before it is re-retrieved from DynamoDB and re-authed with AWS KMS. Provide only one of cacheTTL or cache.")
`cacheTTL` should still be a required parameter, just like in the [MPL for Hierarchical Keyrings](https://github.com/aws/aws-cryptographic-material-providers-library/blob/1169bc8ef34ebfe3937ea3be8acf7a187ef1517a/AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/Model/AwsCryptographyMaterialProvidersTypes.dfy#L909)

2024-11-22 03:36 UTC, texastony commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/ConfigToInfo.dfy
> +    // TODO : Add check that customers only provide either cacheTTL or cache in case of SingleKeyStore
I think this TODO should be removed, right?  
Because Cache's TTL is ALWAYS superseded by   
the cryptographic actor's TTL.

( cryptographic actor :: Searchable Encryption, CMM, Keyring, anything calling a CMC)

2024-11-27 22:55 UTC, RitvikKapila commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/ConfigToInfo.dfy
> +    // TODO : Add check that customers only provide either cacheTTL or cache in case of SingleKeyStore
Yes, I updated the ticket but forgot to update this.

2024-11-27 23:04 UTC, RitvikKapila commented on DynamoDbEncryption/dafny/DynamoDbEncryption/Model/AwsCryptographyDbEncryptionSdkDynamoDbTypes.dfy
> +    nameonly cache: Option<AwsCryptographyMaterialProvidersTypes.CacheType> := Option.None ,
Pass this shared cache like in `MultiKeyStore`

2024-11-28 00:23 UTC, RitvikKapila commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/SearchInfo.dfy
>        }
Add this in the MPL HKeyring getActiveBranchKey and getVersionBranchKey to mitigate risk of swallowing errors
```
// If error is not EntryDoesNotExist, return failure
      if (getCacheOutput.Failure? && !getCacheOutput.error.EntryDoesNotExist?) {
        return Failure(AwsCryptographyMaterialProviders(AwsCryptographyMaterialProviders:=getCacheOutput.error));
      }
```

2024-11-28 00:46 UTC, RitvikKapila commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/SearchInfo.dfy
>        }
Also fix spec duvet for cache entry with limits where it is added

2024-12-04 17:54 UTC, ajewellamz commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/SearchInfo.dfy
> +
I think the following line needs to be
`var getCacheInput := MP.GetCacheEntryInput(identifier := identifier, bytesUsed := None);`

2024-12-04 23:57 UTC, RitvikKapila commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/SearchInfo.dfy
> +
You're right. Thanks Andy.

2025-01-14 01:22 UTC, RitvikKapila commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/SearchInfo.dfy
@Ryan This is where I removed the cache Identifier check from.

2025-01-14 01:23 UTC, RitvikKapila commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/SearchInfo.dfy
>        }
This is not an action item for this PR

2025-01-15 22:34 UTC, RitvikKapila commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/SearchInfo.dfy
>        }
Resolved here https://github.com/aws/aws-cryptographic-material-providers-library/pull/846

2025-01-16 05:58 UTC, seebees requested changes
still need to read the spec, but I think I showed how to prove things about the identifier

2025-01-16 05:58 UTC, seebees commented on DynamoDbEncryption/dafny/DynamoDbEncryption/Model/DynamoDbEncryption.smithy
>    @javadoc("Which type of local cache to use.")
I would keep the docs the same.

```suggestion
  @documentation("Provide the Shared Cache for Searchable Encryption.")
```

2025-01-16 05:58 UTC, seebees commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/ConfigToInfo.dfy
> +    modifies if outer.search.Some? then outer.search.value.versions[0].keyStore.Modifies else {}
These are 0, is there any requirement that `|outer.search.value.versions| == 1`?

2025-01-16 05:58 UTC, seebees commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/ConfigToInfo.dfy
> +    requires ValidSharedCache(config)
Why do you not `ensures ValidSharedCache(config)`? I'm not sure that it matters but I find that ensuring valid stat is just good hygiene.

2025-01-16 05:58 UTC, seebees commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/ConfigToInfo.dfy
> +        // can only hold one element at a time.
I'm not sure I agree.

Consider a system where I use a single config for multiple tables.
Each table has its own configuration
Just because this particular use will only every search for a single HMAC key,
does not mean that any other table used will search for one or even this particular key.

I could use this same CMC, to save allocations, in a `multi` config and expect the partition id
to keep the keys disjoint.

2025-01-16 05:58 UTC, seebees commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/ConfigToInfo.dfy
> +      assume {:axiom} keyStore.Modifies !! cache.Modifies;
What needs this to be true? Can we isolate this axiom a little more?

2025-01-16 05:58 UTC, seebees commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/ConfigToInfo.dfy
> +    }
nit: in dafny an `if` expression can be used for assignment.
```dafny
 var partitionIdBytes :- (if config.multi? && config.multi.partitionId.Some? then
    UTF8.Encode(config.multi.partitionId.value)
  else if config.single? && config.single.partitionId.Some? then
    UTF8.Encode(config.single.partitionId.value)
  else
    I.GenerateUuidBytes()
  )
  .MapFailure(
        e => Error.DynamoDbEncryptionException(
            message := "Could not UTF-8 Encode Partition ID from SingleKeyStore: " + e
          )
      );
```

You will likely have to do some type work if you want to change that, but you get the idea.

2025-01-16 05:58 UTC, seebees commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/ConfigToInfo.dfy
> +    var logicalKeyStoreName : string := getKeyStoreInfoOutput.logicalKeyStoreName;
Dafny's type inference it really good. Given that you don't do it everywhere, I would leave it off generally.

2025-01-16 05:58 UTC, seebees commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/ConfigToInfo.dfy
> +    requires ValidSharedCache(config.keySource)
same note about ensures

2025-01-16 05:58 UTC, seebees commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/ConfigToInfo.dfy
> +    modifies config.keyStore.Modifies
Only keystore? Not the cache?

2025-01-16 05:58 UTC, seebees commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/SearchInfo.dfy
> +    output := Success(uuidBytes);
You can also

```dafny
output := UUID.ToByteArray(uuid)
    .MapFailure(e => Error.DynamoDbEncryptionException(message := e));
```

2025-01-16 05:58 UTC, seebees commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/SearchInfo.dfy
> +          case DontUseKeyId => return Failure(E("KeyID must be supplied with a MultiKeyStore"));
I get confused, @ajewellamz can you verify that this was a typeo?

2025-01-16 05:58 UTC, seebees commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/SearchInfo.dfy
> +          case KeyId(id) => var now := Time.GetCurrent(); var theMap :- getKeysCache(client, stdNames, id, cacheTTL as MP.PositiveLong, partitionIdBytes, logicalKeyStoreNameBytes, now as MP.PositiveL
Long line, lets break it up
```suggestion
          case KeyId(id) =>
            var now := Time.GetCurrent();
            var theMap :- getKeysCache(
              client, stdNames, id,
              cacheTTL as MP.PositiveLong,
              partitionIdBytes,
              logicalKeyStoreNameBytes,
              now as MP.PositiveLong
            );
            return Success(Keys(theMap));
```

2025-01-16 05:58 UTC, seebees commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/SearchInfo.dfy
> +      var cacheDigest :- maybeCacheDigest.MapFailure(e => AwsCryptographyPrimitives(e));
This looks like you are calling `Digest` explicitly. This is your problem. You should call this through the `client`.
I.e. `client.Digest`.

This will allow you to say something like
```dafny 
&& client.History.Digest[?].input.message == resourceId + NULL_BYTE + scopeId + NULL_BYTE + partitionIdBytes + NULL_BYTE + suffix`
&& client.History.Digest[?].output.Success?
&& cacheInput.identifier == client.History.Digest[?].output.value
```

2025-01-16 05:58 UTC, seebees commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/SearchInfo.dfy
Commented below on how to do this.

2025-01-16 05:58 UTC, seebees commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/SearchInfo.dfy
> +      );
This should be proved... See `DigestEnsuresPublicly`

2025-01-16 05:58 UTC, seebees commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/SearchInfo.dfy
> +        expect now < UInt.BoundedInts.INT64_MAX - cacheTTL;
This is a reasonable `expect`. But understand, if this is not true, the caller does not get a nice recoverable error. This halts things. I don't know how hard in each runtime...

2025-01-16 05:58 UTC, seebees commented on DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/src/Index.dfy
> +      :- Need(inputConfig.logicalTableName !in allLogicalTableNames,  E("Duplicate logical table mapped to multiple physical tables: " + inputConfig.logicalTableName));
@ajewellamz  is it space bar heating for me to be worried about this? All we give customers at this time is the error string :(

2025-01-16 21:51 UTC, RitvikKapila commented on DynamoDbEncryption/dafny/DynamoDbEncryption/Model/DynamoDbEncryption.smithy
>    @javadoc("Which type of local cache to use.")
"Provide the Shared Cache for Searchable Encryption." for `MultiKeyStore` is misleading because customers can provide (and have been providing) a Default Cache for instance. This is NOT true for the `SingleKeyStore` because it never took a cache input. I am also inclined towards rejecting a non `Shared` cache for `SingleKeyStore`, just to avoid confusion.

2025-01-16 22:14 UTC, RitvikKapila commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/ConfigToInfo.dfy
> +    modifies if outer.search.Some? then outer.search.value.versions[0].keyStore.Modifies else {}
Yes, that is specified in a `:- Need` statement [here](https://github.com/aws/aws-database-encryption-sdk-dynamodb/blob/21f7fe168cedc0e6553926c7e3808081f172f7b0/DynamoDbEncryption/dafny/DynamoDbEncryption/src/ConfigToInfo.dfy#L58).

2025-01-16 22:15 UTC, RitvikKapila commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/ConfigToInfo.dfy
> +        // can only hold one element at a time.
I propose rejecting all cache inputs which are not shared.

2025-01-16 22:23 UTC, RitvikKapila commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/ConfigToInfo.dfy
> +    }
This is a great idea. But, I want to give different messages for `SingleKeyStore` and `MultiKeyStore`. To my knowledge, that won't work with this type of assignment.

2025-01-16 22:35 UTC, RitvikKapila commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/ConfigToInfo.dfy
> +    requires ValidSharedCache(config)
The cacheType inside config is converted into an actual cache inside `MakeKeySource`. It won't help to ensure ValidState of something we no longer need.

2025-01-16 22:37 UTC, RitvikKapila commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/ConfigToInfo.dfy
> +    var logicalKeyStoreName : string := getKeyStoreInfoOutput.logicalKeyStoreName;
That is a good point. I think I'd want this to be as is just so that its easier for someone who looks at this code to understand where the logicalKeyStoreName (or for that matter the partitionId) is a string and where it is converted into bytes (seq<uint8>).

2025-01-16 22:37 UTC, RitvikKapila commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/ConfigToInfo.dfy
> +    requires ValidSharedCache(config.keySource)
Great point. I don't think it is relevant here though. We can chat about this.

2025-01-16 22:49 UTC, RitvikKapila commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/ConfigToInfo.dfy
> +    modifies config.keyStore.Modifies
I am calling the `GetKeyStoreInfo` for the underlying keyStore. The cache is either fresh, or it doesn't change (because it is `Shared`).

2025-01-16 22:51 UTC, RitvikKapila commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/SearchInfo.dfy
> +    output := Success(uuidBytes);
Great point. Done! Thanks.

2025-01-16 22:56 UTC, RitvikKapila commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/SearchInfo.dfy
> +          case DontUseKeyId => return Failure(E("KeyID must be supplied with a MultiKeyStore"));
I have pinged Andy to look at this. But you do need a KeyId to call `getKeyMap` for a `MultiKeyStore`. Think about it this way, before this change, the code for SingleKeyStore means:
I need the KeyId to be `DontUseKeyId` (which is expected because a SingleKeyStore only handles one KeyId, which it also holds. So you don't need to provide a KeyId.

On the other hand, for a MultiKeyStore, the code is:
If the KeyId is DontUseKeyId, return Failure saying "KeyID must not be supplied with a MultiKeyStore". But the irony is that we did NOT provide a KeyId.

2025-01-16 22:57 UTC, RitvikKapila commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/SearchInfo.dfy
> +          case KeyId(id) => var now := Time.GetCurrent(); var theMap :- getKeysCache(client, stdNames, id, cacheTTL as MP.PositiveLong, partitionIdBytes, logicalKeyStoreNameBytes, now as MP.PositiveL
Great idea, I added the variables one at a time, and didn't realize when it got out of hand lol. Thanks for pointing this out.

2025-01-16 23:38 UTC, RitvikKapila commented on DynamoDbEncryption/dafny/DynamoDbEncryption/Model/DynamoDbEncryption.smithy
>    @javadoc("Which type of local cache to use.")
ToDO(Ritvik): Write more words on doc

2025-01-16 23:42 UTC, RitvikKapila commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/ConfigToInfo.dfy
> +        // can only hold one element at a time.
TODO(Ritvik): Say that the cache is not Shared here.

2025-01-17 00:09 UTC, RitvikKapila commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/SearchInfo.dfy
> +      );
ToDo(Ritvik): Update in MPL.

2025-01-17 01:38 UTC, RitvikKapila commented on DynamoDbEncryption/dafny/DynamoDbEncryption/Model/DynamoDbEncryption.smithy
>    @javadoc("Which type of local cache to use.")
Done

2025-01-17 01:38 UTC, RitvikKapila commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/ConfigToInfo.dfy
> +    requires ValidSharedCache(config)
Done. Thanks

2025-01-17 01:38 UTC, RitvikKapila commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/ConfigToInfo.dfy
> +        // can only hold one element at a time.
Done. Thanks

2025-01-17 01:39 UTC, RitvikKapila commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/ConfigToInfo.dfy
> +      assume {:axiom} keyStore.Modifies !! cache.Modifies;
Done. Thanks

2025-01-17 01:39 UTC, RitvikKapila commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/ConfigToInfo.dfy
> +    requires ValidSharedCache(config.keySource)
Done. Thanks

2025-01-17 01:40 UTC, RitvikKapila commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/SearchInfo.dfy
> +        expect now < UInt.BoundedInts.INT64_MAX - cacheTTL;
I agree. I don't think there's any action item here.

2025-01-17 13:06 UTC, ajewellamz commented on DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/src/Index.dfy
> +      :- Need(inputConfig.logicalTableName !in allLogicalTableNames,  E("Duplicate logical table mapped to multiple physical tables: " + inputConfig.logicalTableName));
1) We must be able to fix bugs and typos or all is lost.
2) It seems unlikely that anyone would write logic based the particular text of a "configuration error" message.

2025-01-17 13:13 UTC, ajewellamz commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/SearchInfo.dfy
> +          case DontUseKeyId => return Failure(E("KeyID must be supplied with a MultiKeyStore"));
```suggestion
          case DontUseKeyId => return Failure(E("Fixed KeyID must not be supplied with a MultiKeyStore"));
```

2025-01-17 21:42 UTC, RitvikKapila commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/SearchInfo.dfy
> +      var cacheDigest :- maybeCacheDigest.MapFailure(e => AwsCryptographyPrimitives(e));
Updated here: https://github.com/aws/aws-database-encryption-sdk-dynamodb/pull/1578

2025-01-17 21:42 UTC, RitvikKapila commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/SearchInfo.dfy
> +          case DontUseKeyId => return Failure(E("KeyID must be supplied with a MultiKeyStore"));
Resolved

2025-01-22 23:14 UTC, seebees commented on specification/searchable-encryption/search-config.md
> +  it unique for every [Beacon Key Source](#beacon-key-source). In this case, two [Beacon Key Sources](#beacon-key-source) (or another Material Provider)
There are a few places where newlines would be nice in the spec.
```suggestion
  it unique for every [Beacon Key Source](#beacon-key-source).
  In this case, two [Beacon Key Sources](#beacon-key-source) (or another Material Provider)
```

2025-01-22 23:14 UTC, seebees commented on specification/searchable-encryption/search-config.md
> +  CANNOT share the same cache entries in the cache.
https://datatracker.ietf.org/doc/html/rfc2119 do you mean MUST NOT?

2025-01-22 23:14 UTC, seebees commented on specification/searchable-encryption/search-config.md
> +  CANNOT share the same cache entries in the cache.
I think you mean will not.

2025-01-22 23:14 UTC, seebees commented on specification/searchable-encryption/search-config.md
> +> Note: Users MUST NEVER have two different physical Key Stores with the same Logical Key Store Name.
This is not a requirement that we can enforce.
And also, it is... nuanced. They can be the same, provided they can treat the physical stores as the same and ensure uniqueness.
Like a DDB global table. 

```suggestion
> Note: Users should not have two different physical Key Stores with the same Logical Key Store Name.
```

2025-01-22 23:14 UTC, seebees commented on specification/searchable-encryption/search-config.md
> +the [beacon versions](#beacon-version-initialization). This is a logical name for the key store.
```suggestion
the [beacon versions](#beacon-version-initialization).
This is a logical name for the key store.
```

2025-01-23 00:21 UTC, RitvikKapila commented on specification/searchable-encryption/search-config.md
> +> Note: Users MUST NEVER have two different physical Key Stores with the same Logical Key Store Name.
That makes sense. Updated. Thanks.

2025-01-23 00:23 UTC, RitvikKapila commented on specification/searchable-encryption/search-config.md
> +  CANNOT share the same cache entries in the cache.
Yes I mean WILL NOT. Thanks for pointing out.

2025-01-23 00:24 UTC, RitvikKapila commented on specification/searchable-encryption/search-config.md
> +cache entries.
We cannot ensure this. I'll remove the MUST to make it should (not caps).

2025-01-23 00:28 UTC, RitvikKapila commented on specification/searchable-encryption/search-config.md
> +A Hex value that indicates if an element is from a Caching_CMM, Hierarchical_Keyring, or some other future resource.
Good catch. Done. Thanks.

2025-01-23 00:33 UTC, RitvikKapila commented on specification/searchable-encryption/search-config.md
> +In all other cases, the Key Store Cache MUST be bound to the [Beacon Key Source](#beacon-key-source).
I'll remove the caps. Thanks for pointing this out.

2025-01-23 00:37 UTC, RitvikKapila commented on specification/searchable-encryption/search-config.md
> +If this is NOT true, then we MUST treat the cache entry as expired.
Right now its right after the Seachable Encryption Cache Identifier. I'll move it further up.

2025-01-23 00:39 UTC, RitvikKapila commented on specification/searchable-encryption/search-config.md
> +MUST be the same.
Yes, this does read better. Thanks!

2025-01-23 00:40 UTC, RitvikKapila commented on specification/searchable-encryption/search-config.md
> +In all other cases, the Key Store Cache MUST be bound to the [Beacon Key Source](#beacon-key-source).
Updated

2025-01-23 00:43 UTC, RitvikKapila commented on specification/searchable-encryption/search-config.md
> +of the provided `CacheType` to 1, because the [Single Key Store](#single-key-store-initialization) only ever caches one entry. Even if the user provides an entryCapacity > 1, the [Single Key Store](#
I was trying to put a note here about the comment we discussed about. But I don't think there's anything to enforce here so to avoid confusion, I'm just going to remove it. Thanks for pointing this out.

2025-01-23 00:44 UTC, RitvikKapila commented on specification/searchable-encryption/search-config.md
> +For a [Single Key Store](#single-key-store-initialization), either the user provides a cache, or we create a cache that MUST have [Entry Capacity](../../submodules/MaterialProviders/aws-encryption-sd
This is how it is created right now. There are no other enforcing "Need" or "ensures" clauses, so I'll remove the caps. Saying something like, "either the user provides a cache, or we create a cache that has Entry Capacity equal to 1"

2025-01-23 23:00 UTC, seebees approved these changes
LGTM

2025-01-24 00:50 UTC, merged