feat: add more attributes to encryption context
aws/aws-database-encryption-sdk-dynamodb pull request #719
Opened 2024-01-16 19:56 UTC by ajewellamz

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-02-07 19:42 UTC, seebees requested changes
I think the only change in all that is that v3 should be an error, not part of the else.

2024-02-07 19:46 UTC, ajewellamz commented on SharedMakefile.mk
> +	--dafny-version 4.1 \
The version of smithy-dafny I'm working with is still broken, and specifying --dafny-version 4.2 gets you 4.3, which breaks everything.

2024-02-07 19:47 UTC, ajewellamz commented on DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/src/Index.dfy
> +  import IE_Types = AwsCryptographyDbEncryptionSdkDynamoDbItemEncryptorTypes
Yes

2024-02-07 19:48 UTC, ajewellamz commented on DynamoDbEncryption/dafny/DynamoDbItemEncryptor/src/AwsCryptographyDbEncryptionSdkDynamoDbItemEncryptorOperations.dfy
> +      "internal error"
Because Dafny is broken, and CSE.DO_NOTHING is no longer a "literal" and therefore matches everything.

2024-02-07 19:53 UTC, ajewellamz commented on DynamoDbEncryption/dafny/DynamoDbItemEncryptor/src/AwsCryptographyDbEncryptionSdkDynamoDbItemEncryptorOperations.dfy
> -                                              )
because the ParsedHeader now has selectorContext, which comes from ConvertContextForSelector, which s a method, which you can't put in an ensures.

2024-02-07 19:53 UTC, ajewellamz commented on DynamoDbEncryption/dafny/DynamoDbItemEncryptor/src/AwsCryptographyDbEncryptionSdkDynamoDbItemEncryptorOperations.dfy
> -                                              )
because the ParsedHeader now has selectorContext, which comes from ConvertContextForSelector, which s a method, which you can't put in an ensures.

2024-02-07 19:55 UTC, ajewellamz commented on DynamoDbEncryption/dafny/StructuredEncryption/src/AwsCryptographyDbEncryptionSdkStructuredEncryptionOperations.dfy
> -      //= type=implication
I think so. We really need to make format required, like you did in the MPL.

2024-02-07 19:56 UTC, ajewellamz commented on DynamoDbEncryption/dafny/StructuredEncryption/src/AwsCryptographyDbEncryptionSdkStructuredEncryptionOperations.dfy
> +      assume {:axiom} input.cmm.Modifies !! {config.materialProviders.History};
I have no doubt that it's true, I just don't know how to convince Dafny of that.

2024-02-07 19:57 UTC, ajewellamz commented on specification/dynamodb-encryption-client/encrypt-item.md
> -  - the [value](#base-context-value) of the Partition Key.
Yes, except v1 is slightly more complicated than that.

2024-02-07 20:04 UTC, ajewellamz commented on specification/structured-encryption/encrypt-structure.md
> +The Legend MUST be named "aws-crypto-legend" and be a string with one character per attribute added above,
That's what ", plus the Legend." means.

2024-02-07 20:06 UTC, ajewellamz commented on TestVectors/dafny/DDBEncryption/src/WriteManifest.dfy
We already have tests with attributes other than the keys as SIGN_AND_INCLUDE_IN_ENCRYPTION_CONTEXT, both in the TestVectors and the ItemEncryptor unit tests.

2024-02-07 20:06 UTC, ajewellamz commented on DynamoDbEncryption/dafny/DynamoDbEncryptionTransforms/test/TestFixtures.dfy
> +  }
We already have tests with attributes other than the keys as SIGN_AND_INCLUDE_IN_ENCRYPTION_CONTEXT, both in the TestVectors and the ItemEncryptor unit tests.

2024-02-08 17:20 UTC, seebees commented on specification/dynamodb-encryption-client/encrypt-item.md
> -  - the [value](#base-context-value) of the Partition Key.
Ok. Given that customers will need to change any policy that the may have anyway. I can see why consistency is better in this case. I didn't see this called out in the spec and that would be nice to add.

2024-02-08 17:21 UTC, seebees commented on TestVectors/dafny/DDBEncryption/src/WriteManifest.dfy
I think I found such tests. In my reading it was not clear where they are

2024-02-08 17:22 UTC, seebees commented on SharedMakefile.mk
> +	--dafny-version 4.1 \
Hum, so then we need some comment here. Since it is confusing to me that the code is using the 4.2 runtime, but this says 4.1

2024-02-08 17:29 UTC, seebees commented on DynamoDbEncryption/dafny/DynamoDbItemEncryptor/src/AwsCryptographyDbEncryptionSdkDynamoDbItemEncryptorOperations.dfy
> +      "internal error"
Would this be better handled with a `requires`?

2024-02-08 17:36 UTC, ajewellamz commented on SharedMakefile.mk
> +	--dafny-version 4.1 \
But the runtime doesn't matter. This is smithy-dafny, and we're just picking what format the output should be in.

2024-02-08 18:05 UTC, ajewellamz commented on DynamoDbEncryption/dafny/DynamoDbItemEncryptor/src/AwsCryptographyDbEncryptionSdkDynamoDbItemEncryptorOperations.dfy
> +      "internal error"
assert false added.

2024-02-08 19:41 UTC, seebees commented on specification/dynamodb-encryption-client/encrypt-item.md
> -  - the [value](#base-context-value) of the Partition Key.
Oh, good.

2024-02-08 19:43 UTC, seebees commented on SharedMakefile.mk
> +	--dafny-version 4.1 \
we just need the comment

2024-02-08 19:49 UTC, seebees commented on DynamoDbEncryption/dafny/DynamoDbItemEncryptor/src/AwsCryptographyDbEncryptionSdkDynamoDbItemEncryptorOperations.dfy
> +      assert false;
```suggestion
      assert false by {
        assert action != CSE.DO_NOTHING;
        assert action != CSE.SIGN_ONLY;
        assert action != CSE.SIGN_AND_INCLUDE_IN_ENCRYPTION_CONTEXT;
        assert action != CSE.ENCRYPT_AND_SIGN;
      }
```

2024-03-18 20:52 UTC, ajewellamz commented on specification/changes/2024-02-29-encryption-context/change.md
All of that is in background.md

2024-03-18 21:31 UTC, seebees commented on DynamoDbEncryption/dafny/StructuredEncryption/src/AwsCryptographyDbEncryptionSdkStructuredEncryptionOperations.dfy
> +        encryptionContext := encryptionContext + newEncryptionContext;
What happens if there is an overlap?

2024-03-18 21:32 UTC, seebees commented on DynamoDbEncryption/dafny/StructuredEncryption/src/AwsCryptographyDbEncryptionSdkStructuredEncryptionOperations.dfy
> +        encryptionContext := encryptionContext + newEncryptionContext;
Same question

2024-03-18 21:37 UTC, ajewellamz commented on DynamoDbEncryption/dafny/StructuredEncryption/src/AwsCryptographyDbEncryptionSdkStructuredEncryptionOperations.dfy
> +        encryptionContext := encryptionContext + newEncryptionContext;
Then something very strange has happened. 
If newEncryptionContext; is non-empty, then newEncryptionContext is entirely attributes and encryptionContext has no attributes.

2024-03-18 21:38 UTC, ajewellamz commented on DynamoDbEncryption/dafny/StructuredEncryption/src/AwsCryptographyDbEncryptionSdkStructuredEncryptionOperations.dfy
> +        encryptionContext := encryptionContext + newEncryptionContext;
Same answer.

2024-03-18 22:09 UTC, seebees commented on DynamoDbEncryption/dafny/StructuredEncryption/src/AwsCryptographyDbEncryptionSdkStructuredEncryptionOperations.dfy
> +        encryptionContext := encryptionContext + newEncryptionContext;
I think that we should have an error is they overlap.
I don't know what such a call would be. And all the callers of this method should agree.
But this may not always be true.

2024-03-18 22:11 UTC, seebees commented on DynamoDbEncryption/dafny/StructuredEncryption/src/AwsCryptographyDbEncryptionSdkStructuredEncryptionOperations.dfy
> +        encryptionContext := encryptionContext + newEncryptionContext;
Something like
`:- Need(|x !! y| == 0, "Internal Error")`

or

```dafny
  var oldEncryptionContextLength := |encryptionContext|;
  encryptionContext := encryptionContext + newEncryptionContext;
  :- Need(|encryptionContext| == oldEncryptionContextLength + newEncryptionContext, "Duplicate ...");
```

I suppose we could some day check to only error if the values differ...

2024-03-18 22:12 UTC, seebees requested changes
We should just deny this option.
Then I'm good (both encrypt/decrypt)

https://github.com/aws/aws-database-encryption-sdk-dynamodb/pull/719/files/6997b8e8d09bde02870cdbd6a60199d9248f43cb..5b5a48f2e6e92570b99b8930b10cebf7a09e8d36#r1529350777

2024-03-18 22:46 UTC, ajewellamz commented on DynamoDbEncryption/dafny/StructuredEncryption/src/AwsCryptographyDbEncryptionSdkStructuredEncryptionOperations.dfy
> +        encryptionContext := encryptionContext + newEncryptionContext;
Done. Added to spec and added duvet annotation.

2024-03-18 23:42 UTC, seebees approved these changes
LGTM

2024-03-18 23:44 UTC, merged