Add GetEncryptedDataKeyDescription operation
aws/aws-database-encryption-sdk-dynamodb pull request #856
Opened 2024-03-25 21:52 UTC by rishav-karanjit

*Issue #, if available:*

*Description of changes:*
This PR adds GetEncryptedDataKeyDescription to DynamoDbEncryption.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-04-09 18:42 UTC, ajewellamz commented on specification/dynamodb-encryption-client/ddb-get-encrypted-data-key-description.md
> +This operation MUST return a list of following:
```suggestion
This operation MUST return the following:
```

2024-04-09 18:52 UTC, ajewellamz commented on specification/dynamodb-encryption-client/ddb-get-encrypted-data-key-description.md
> +This operation should behave in following ways:
This line could be deleted.

2024-04-09 19:16 UTC, ajewellamz commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/AwsCryptographyDbEncryptionSdkDynamoDbOperations.dfy
> +        :- Need(DynamoToStruct.ItemToStructured(plaintextItem).Success?, E("Failed to convert AttributeMap to StructuredDataMap."));
You shouldn't call ItemToStructured twice. Skip this first call and just use
header :- ItemToStructured()

Also, don't use ItemToStructured at all
plainTextItem["aws_dbe_head"].B
is already the bytes you need.

2024-04-09 19:20 UTC, ajewellamz commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/AwsCryptographyDbEncryptionSdkDynamoDbOperations.dfy
> +    var deserializedHeader := Header.PartialDeserialize(header);
Don't call PartialDeserialize twice.
Just
var deserializedHeader :- Header.PartialDeserialize(header);

I don't think I have ever called Extract().

2024-04-09 19:20 UTC, ajewellamz commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/AwsCryptographyDbEncryptionSdkDynamoDbOperations.dfy
> +      :- Need(UTF8.Decode(datakeys[i].keyProviderId).Success?, E("Failed to extract keyProviderId."));
Same here. One call with `:-`

2024-04-09 19:22 UTC, ajewellamz commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/AwsCryptographyDbEncryptionSdkDynamoDbOperations.dfy
> +      if |extractedKeyProviderId| < 7 || extractedKeyProviderId[0..7] != "aws-kms" {
You could also say
`if !("aws-kms" < extractedKeyProviderId) {`
because in Dafny `<` on strings means `prefix`.

2024-04-09 19:24 UTC, ajewellamz commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/AwsCryptographyDbEncryptionSdkDynamoDbOperations.dfy
> +      // Format flavor is either 0 or 1
This looks like you're trying for a Duvet annotation, but this isn't quite that.

2024-04-09 19:27 UTC, ajewellamz commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/AwsCryptographyDbEncryptionSdkDynamoDbOperations.dfy
> +        var EDK_CIPHERTEXT_BRANCH_KEY_VERSION_INDEX := 12 + 16;
can you add
const SALT_LENGTH : int = 16
and such, and then use those in the code?

2024-04-09 19:33 UTC, ajewellamz commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/AwsCryptographyDbEncryptionSdkDynamoDbOperations.dfy
> +      var singleDataKeyOutput : EncryptedDataKeyDescriptionOutput;
It might be nice to extract the contents of this loop into a function (not a method), to reduce clutter.
So this loop would just be
for i := 0 to |datakeys| {
   var singleDataKeyOutput :- ExtractDataKeyOutput(datakeys[i])
   list := list + [singleDataKeyOutput];
}

2024-04-09 19:50 UTC, ajewellamz commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/AwsCryptographyDbEncryptionSdkDynamoDbOperations.dfy
> +        singleDataKeyOutput := EncryptedDataKeyDescriptionOutput(
Just a style thing, feel free to ignore, but there's a fair amount of redundancy,  constructing a EncryptedDataKeyDescriptionOutput in three different places and saying `keyProviderId := extractedKeyProviderId` in three different places.
If instead you collected keyProviderId and such separately, you could construct the EncryptedDataKeyDescriptionOutput just before you put it in the list.

2024-04-09 19:50 UTC, ajewellamz commented on DynamoDbEncryption/dafny/DynamoDbEncryption/Model/DynamoDbEncryption.smithy
> +structure EncryptedDataKeyDescriptionOutput {
```suggestion
structure EncryptedDataKeyDescription {
```

2024-04-09 19:53 UTC, ajewellamz commented on DynamoDbEncryption/dafny/DynamoDbEncryption/test/DynamoDbGetEncryptedDataKeyDescriptionTest.dfy
> +    var actualDataKeyDescription := ddbEncResources.GetEncryptedDataKeyDescription(inputVariable);
```suggestion
    var actualDataKeyDescription :- expect ddbEncResources.GetEncryptedDataKeyDescription(inputVariable);
```
then skip all the Extract calls.

2024-04-09 19:54 UTC, ajewellamz commented on DynamoDbEncryption/dafny/DynamoDbEncryption/test/DynamoDbGetEncryptedDataKeyDescriptionTest.dfy
> +    expect UTF8.Decode(expectedHead.dataKeys[0].keyProviderId).Success?;
```suggestion
    var keyProviderId :- expect UTF8.Decode(expectedHead.dataKeys[0].keyProviderId);
```

2024-04-11 15:06 UTC, rishav-karanjit commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/AwsCryptographyDbEncryptionSdkDynamoDbOperations.dfy
> +      if |extractedKeyProviderId| < 7 || extractedKeyProviderId[0..7] != "aws-kms" {
`<=` will be more appropriate because `<` is a proper prefix and `<=` is prefix which can catch `aws-kms` as well.

2024-04-11 15:09 UTC, rishav-karanjit commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/AwsCryptographyDbEncryptionSdkDynamoDbOperations.dfy
> +      var singleDataKeyOutput : EncryptedDataKeyDescriptionOutput;
New code where EncryptedDataKeyDescriptionOutput was only created once reduced clutter. So, a new function was not created.

2024-04-11 15:37 UTC, ajewellamz commented on DynamoDbEncryption/dafny/DynamoDbEncryption/src/AwsCryptographyDbEncryptionSdkDynamoDbOperations.dfy
> +    //= type=implication
Not an implication, just a citation. Remove this line, and all the similar lines within the body of this function.

2024-04-11 19:03 UTC, ajewellamz submitted a review, later dismissed
Looks good to me. You probably want someone else's opinion.

2024-04-17 21:38 UTC, justplaz commented on DynamoDbEncryption/dafny/DynamoDbEncryption/test/DynamoDbGetEncryptedDataKeyDescriptionTest.dfy
> +  const algorithmSuite := AlgorithmSuites.DBE_ALG_AES_256_GCM_HKDF_SHA512_COMMIT_KEY_ECDSA_P384_SYMSIG_HMAC_SHA384
nit: should we test against other AlgorithmSuites? I guess just `ALG_AES_256_GCM_HKDF_SHA512_COMMIT_KEY_SYMSIG_HMAC_SHA384`

2024-04-17 21:38 UTC, justplaz commented on DynamoDbEncryption/dafny/DynamoDbEncryption/test/DynamoDbGetEncryptedDataKeyDescriptionTest.dfy
> +
nit: are there failure cases which should be tested, in addition to the `Success` cases?

2024-04-17 21:38 UTC, justplaz commented on Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/GetEncryptedDataKeyDescriptionExample.java
> +        assert output.EncryptedDataKeyDescriptionOutput().get(0).keyProviderId().equals(expectedKeyProviderId);
this isn't your fault,
but `assert` statements are **disabled by default in Java**.
this means they are ignored unless explicitly enabled either in JVM configurations or in a wrapper (i.e. gradle). 
you can confirm this by writing `assert false` and running the examples. 
it shouldn't block this PR, but if you have time, please take some to set `enableAssertions` to `true` in gradle (and fix any failed assertions we may have...)

2024-04-18 23:04 UTC, rishav-karanjit commented on Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/GetEncryptedDataKeyDescriptionExample.java
> +        assert output.EncryptedDataKeyDescriptionOutput().get(0).keyProviderId().equals(expectedKeyProviderId);
I tried this and `assert false` made my Gradle test fail.

2024-05-01 04:04 UTC, texastony requested changes
Blocking on a lack of User Documentation (`@JavaDoc` in the Smithy Model).

Though... I hope we can improve the `plaintextItem` name...

2024-05-01 04:04 UTC, texastony commented on specification/dynamodb-encryption-client/ddb-get-encrypted-data-key-description.md
> +- If the input is a encrypted DynamoDB item, it MUST attempt to extract "aws_dbe_head" attribute from the DynamoDB item to get binary header.
```suggestion
- If the input is an encrypted DynamoDB item, it MUST attempt to extract "aws_dbe_head" attribute from the DynamoDB item to get the binary header. 
```

2024-05-01 04:04 UTC, texastony commented on specification/dynamodb-encryption-client/ddb-get-encrypted-data-key-description.md
> +    - If the Data Key does not belong to AWS Cryptographic Materials Provider Keyring, the operation will only return keyProviderId.
Right now, if the Data Key was not created by a KMS Keyring, the operation will only return the keyProviderId.

Is that your intention?

2024-05-06 15:26 UTC, rishav-karanjit commented on specification/dynamodb-encryption-client/ddb-get-encrypted-data-key-description.md
> +    - If the Data Key does not belong to AWS Cryptographic Materials Provider Keyring, the operation will only return keyProviderId.
Yes

2024-05-09 18:53 UTC, texastony requested changes

2024-05-09 18:53 UTC, texastony commented on Examples/runtimes/net/src/GetEncryptedDataKeyDescriptionExample.cs
Blocking: I think `PlaintextItem` is still present in the examples.

2024-05-09 18:53 UTC, texastony commented on Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/GetEncryptedDataKeyDescriptionExample.java
Blocking: Still need to update Plaintext item in example:
https://github.com/aws/aws-database-encryption-sdk-dynamodb/blob/9b58508b3053cb1e7964c56f7b337f9bd20dfa8a/Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/GetEncryptedDataKeyDescriptionExample.java#L52

2024-05-10 03:49 UTC, rishav-karanjit commented on Examples/runtimes/net/src/GetEncryptedDataKeyDescriptionExample.cs
I double checked in my branch and diff. I think you are looking at one of my old commit? I had made this change in [6b30e4c](https://github.com/aws/aws-database-encryption-sdk-dynamodb/pull/856/commits/6b30e4c06fd659034b68a82ebb07203354a36300) after CI for examples failed at [6dedc67](https://github.com/aws/aws-database-encryption-sdk-dynamodb/pull/856/commits/6dedc67fd3721dadba61fe4649c95ea53c19aad3)

2024-05-10 03:51 UTC, rishav-karanjit commented on Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/GetEncryptedDataKeyDescriptionExample.java
Yeah, for some reason GitHub showed you [9b58508](https://github.com/aws/aws-database-encryption-sdk-dynamodb/commit/9b58508b3053cb1e7964c56f7b337f9bd20dfa8a) instead of the latest commit. This comment is at [9b58508](https://github.com/aws/aws-database-encryption-sdk-dynamodb/commit/9b58508b3053cb1e7964c56f7b337f9bd20dfa8a) not on latest commit.

2024-05-10 16:32 UTC, texastony approved these changes

2024-05-10 17:05 UTC, merged